FROM quay.io/keycloak/keycloak:21.1.0-0 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=mariadb

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:21.1.0-0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running mariadb instance
ENV KC_DB=${variable:-mariadb}
ENV KC_DB_URL=${variable:-jdbc:mariadb://mariadb-container:3306/keycloak-database}
ENV KC_DB_USERNAME=${variable:-dbuser}
ENV KC_DB_PASSWORD=${variable:-dbpassword}
ENV KC_HOSTNAME=${variable:-localhost}
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]