# Dockerfile for lighttpd

FROM alpine:edge

ENV LIGHTTPD_VERSION=1.4.67-r0

RUN addgroup -g 1001 -S servidor && adduser -u 1001 -S servidor -G servidor -H

RUN apk add --update --no-cache \
	lighttpd=${LIGHTTPD_VERSION} \
	lighttpd-mod_auth \
  && rm -rf /var/cache/apk/*

COPY arquivos/etc/lighttpd/* /etc/lighttpd/
COPY arquivos/start.sh /usr/local/bin/

EXPOSE 80
EXPOSE 443

VOLUME /srv
VOLUME /etc/lighttpd

RUN chmod +x /usr/local/bin/start.sh

CMD ["/usr/local/bin/start.sh"]
