name: Ts3AudioBot

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths: 
      - 'imagens/ts3audiobot/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./imagens/ts3audiobot/0.12.2/Dockerfile.stable
            platforms: linux/amd64,linux/arm64
            tags: igorferreir4/ts3audiobot:0.12.2
            cache: type=gha
            nomedocache: ts3bot-stable

          - dockerfile: ./imagens/ts3audiobot/0.13.0-alpha.41/Dockerfile.alpha
            platforms: linux/amd64,linux/arm64,linux/arm/v7
            tags: igorferreir4/ts3audiobot:0.13.0-a41 , igorferreir4/ts3audiobot:latest
            cache: type=gha
            nomedocache: ts3bot-alpha
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurando QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurando Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Logando no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: imagens/ts3audiobot/
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          cache-from: ${{ matrix.cache }},scope=build-${{ matrix.nomedocache }}
          cache-to: ${{ matrix.cache }},scope=build-${{ matrix.nomedocache }},mode=max

      - name: Update README.md Docker
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ github.repository_owner }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: igorferreir4/ts3audiobot
          readme: imagens/ts3audiobot/README.md
          description: Splamy/TS3AudioBot for amd64, arm64 and armv7